server:
  port: 8936
  servlet:
    context-path: /api/v1
spring:
  application:
    name: ganbaro-server
  datasource:
    url: jdbc:postgresql://debian.yuki.im:5432/db_ganbaro
    driver-class-name: org.postgresql.Driver
    username: ganbaro
    password: KKlwyTksFDV4eTWGQmZproJbV
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
mybatis:
  mapper-locations: classpath:mapper/*.xml
